### ISSUE TITLE
Problem editing previous event

### ISSUE THREAD

**Issue by adelq** [pennlabs/common-funding-application#226]
"There's some sort of bug that doesn't allow me to open an application I've already submitted. Many of the funding boards have asked me to send a copy of our common funding app because they can't get access to it either. When I try to click "edit" on the app we've submitted, an error pops up on the screen. I've attached a screenshot of it below."
![screen_shot_2015-02-01_at_7 05 00_pm](https://cloud.githubusercontent.com/assets/929309/6004038/16a589e2-aace-11e4-93b3-55491d57dd98.png)

**Comment by honki91** [comment]
I fixed the problem for the single event by manually deleting unnecessary answer data, but  potentially issue still exist. The error above occurred because three same response objects to the single question was recorded in the DB. I don't know how this could have occurred, but the event page crashes in this case because it assumes only one answer exists in the DB for each question.

**Comment by adelq** [comment]
Can no longer reproduce
